name: main

on:
  push:
    branches:
      - main

jobs:
  source-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: format
        run: make format
      - name: unit test
        run: make unit-test

  binary-checks:
    env:
      TAG: ${{ github.sha }}
    needs: source-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: build docker image
        run: make docker-build
      - name: run docker container
        run: make docker-run
      - name: run integration tests
        run: make integration-test
      - name: stop docker container
        run: make docker-stop

  deploy:
    runs-on: ubuntu-latest
    needs: binary-checks
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "yumseng" #Must be unique in Heroku
          heroku_email: "103879u@gmail.com"
          usedocker: true
          docker_build_args:
            - TAG